# Control streams from NONMEM 7.5 examples

nmex_control3 <- c(
  "$PROBLEM  THEOPHYLLINE   SINGLE SUBJECT DATA",
  "$INPUT  DOSE=AMT TIME CP=DV",
  "$DATA  DATA3",
  "$SUBROUTINES  ADVAN2",
  "",
  "$PK",
  "CALLFL=1",
  "KA=THETA(1)",
  "K=THETA(2)",
  "SC=THETA(3)",
  "",
  "$ERROR",
  "Y=F+ERR(1)",
  "",
  "$THETA  (0,1.7)  (0,.102)  (0,29)",
  "",
  "$ESTIMATION  MAXEVAL=240  PRINT=2",
  "$COVR",
  "$TABLE TIME",
  "$SCAT    CP VS TIME",
  "$SCAT    PRED VS TIME",
  "$SCAT    RES VS TIME"
)

nmex_ccontrs <- c(
  "$PROBLEM",
  "$DATA NMDATA7.CSV",
  "$INPUT ID DV",
  "$SUB CONTR=CONTR.txt CCONTR=CCONTR.txt",
  "$PRED",
  "     W=THETA(2)                 ;SD",
  "     CL=THETA(1)*EXP(ETA(1))    ;CL/F",
  "     PRE=1/CL                   ; SS ASSUMING INPUT RATE = 1",
  "     LAM=THETA(3)",
  "     Y=(PRE**LAM-1)/LAM+EPS(1)*W",
  "     RES1=(DV-PRE)/W",
  "$THETA",
  "     (0,.1)      ;CL/F",
  "     (0,2)       ;SD ADDITIVE",
  "     (0,.251)       ;BOX COX LAMBDA PARAMETER",
  "$OMEGA",
  "     .003",
  "$SIGMA",
  "     1 FIX",
  "$EST MAXEVALS=9999 METH=1 PRINT=1",
  "$COV PRINT=E"
)

# This has the same content as the bayes1 example, minus some comments and blank
# lines.
nmex_bayes1 <- c(
  ";Model Desc: Two compartment Model, Using ADVAN3, TRANS4",
  ";Project Name: nm7examples",
  "",
  "$PROB RUN# Example 1 (from samp5l)",
  "$INPUT C SET ID JID TIME  DV=CONC AMT=DOSE RATE EVID MDV CMT CLX",
  "       V1X QX V2X SDIX SDSX",
  "$DATA example1.csv IGNORE=C",
  "$SUBROUTINES ADVAN3 TRANS4",
  "",
  "$PK",
  "MU_1=THETA(1)",
  "MU_2=THETA(2)",
  "MU_3=THETA(3)",
  "MU_4=THETA(4)",
  "CL=DEXP(MU_1+ETA(1))",
  "V1=DEXP(MU_2+ETA(2))",
  "Q=DEXP(MU_3+ETA(3))",
  "V2=DEXP(MU_4+ETA(4))",
  "S1=V1",
  "",
  "$ERROR",
  "Y = F + F*EPS(1)",
  "",
  "; Initial values of THETA",
  "$THETA",
  "(0.001, 2.0) ;[LN(CL)]",
  "(0.001, 2.0) ;[LN(V1)]",
  "(0.001, 2.0) ;[LN(Q)]",
  "(0.001, 2.0) ;[LN(V2)]",
  "",
  ";INITIAL values of OMEGA",
  "$OMEGA BLOCK(4)",
  "0.15   ;[P]",
  "0.01  ;[F]",
  "0.15   ;[P]",
  "0.01  ;[F]",
  "0.01  ;[F]",
  "0.15   ;[P]",
  "0.01  ;[F]",
  "0.01  ;[F]",
  "0.01  ;[F]",
  "0.15   ;[P]",
  "",
  ";Initial value of SIGMA",
  "$SIGMA",
  "(0.6 )   ;[P]",
  "",
  "$PRIOR NWPRI",
  "",
  "; Prior information of THETAS",
  "$THETAP (2.0 FIX)X4",
  "",
  "$THETAPV BLOCK(4) FIX VALUES(10000,0.0)",
  "",
  "; Prior information to the OMEGAS.",
  "$OMEGAP BLOCK(4) FIX VALUES(0.2,0.0)",
  "$OMEGAPD (4 FIX)",
  "",
  "; Prior information to the SIGMAS",
  "$SIGMAP 0.06 FIX",
  "$SIGMAPD (1 FIX)",
  "",
  "$EST METHOD=ITS MAPITER=0 INTERACTION FILE=example1.ext NITER=500",
  "     PRINT=5 NOABORT SIGL=4 CTYPE=3 CITER=10",
  "     CALPHA=0.05 NOPRIOR=1 NSIG=2",
  "",
  "$EST METHOD=SAEM INTERACTION NBURN=3000 NITER=500 PRINT=100",
  "     SEED=1556678 ISAMPLE=2",
  "",
  "$EST METHOD=IMP  INTERACTION EONLY=1 NITER=5 ISAMPLE=3000 PRINT=1",
  "     SIGL=8 NOPRIOR=1",
  "",
  "",
  "$EST METHOD=BAYES INTERACTION FILE=example1.txt NBURN=10000",
  "     NITER=10000 PRINT=100 NOPRIOR=0",
  "",
  "$EST METHOD=COND INTERACTION MAXEVAL=9999 NSIG=3 SIGL=10",
  "     PRINT=5 NOABORT NOPRIOR=1",
  "     FILE=example1.ext",
  "",
  "$COV MATRIX=R PRINT=E UNCONDITIONAL SIGL=12",
  "",
  "$TABLE ID TIME PRED RES WRES CPRED CWRES EPRED ERES EWRES NOAPPEND",
  "       ONEHEADER FILE=example1.TAB NOPRINT",
  "$TABLE ID CL V1 Q V2 FIRSTONLY NOAPPEND NOPRINT FILE=example1.PAR",
  "$TABLE ID ETA1 ETA2 ETA3 ETA4 FIRSTONLY NOAPPEND",
  "        NOPRINT FILE=example1.ETA"
)
