#' Environment containing control stream examples
#'
#' These are selected from NONMEM 7.5 examples. Some comments and blank lines
#' have been removed.
#'
#' @examples
#'
#' # Get list of available examples.
#' ls(nmrec_examples)
#'
#' # Parse an example into an `nmrec_ctl_records` object.
#' ctl <- parse_ctl(get("bayes1", envir = nmrec_examples))
#' head(ctl$records)
#'
#' @name nmrec_examples
NULL

nmex_control3 <- c(
  "$PROBLEM  THEOPHYLLINE   SINGLE SUBJECT DATA",
  "$INPUT  DOSE=AMT TIME CP=DV",
  "$DATA  DATA3",
  "$SUBROUTINES  ADVAN2",
  "",
  "$PK",
  "CALLFL=1",
  "KA=THETA(1)",
  "K=THETA(2)",
  "SC=THETA(3)",
  "",
  "$ERROR",
  "Y=F+ERR(1)",
  "",
  "$THETA  (0,1.7)  (0,.102)  (0,29)",
  "",
  "$ESTIMATION  MAXEVAL=240  PRINT=2",
  "$COVR",
  "$TABLE TIME",
  "$SCAT    CP VS TIME",
  "$SCAT    PRED VS TIME",
  "$SCAT    RES VS TIME"
)

nmex_ccontrs <- c(
  "$PROBLEM",
  "$DATA NMDATA7.CSV",
  "$INPUT ID DV",
  "$SUB CONTR=CONTR.txt CCONTR=CCONTR.txt",
  "$PRED",
  "     W=THETA(2)                 ;SD",
  "     CL=THETA(1)*EXP(ETA(1))    ;CL/F",
  "     PRE=1/CL                   ; SS ASSUMING INPUT RATE = 1",
  "     LAM=THETA(3)",
  "     Y=(PRE**LAM-1)/LAM+EPS(1)*W",
  "     RES1=(DV-PRE)/W",
  "$THETA",
  "     (0,.1)      ;CL/F",
  "     (0,2)       ;SD ADDITIVE",
  "     (0,.251)       ;BOX COX LAMBDA PARAMETER",
  "$OMEGA",
  "     .003",
  "$SIGMA",
  "     1 FIX",
  "$EST MAXEVALS=9999 METH=1 PRINT=1",
  "$COV PRINT=E"
)

nmex_bayes1 <- c(
  ";Model Desc: Two compartment Model, Using ADVAN3, TRANS4",
  ";Project Name: nm7examples",
  "",
  "$PROB RUN# Example 1 (from samp5l)",
  "$INPUT C SET ID JID TIME  DV=CONC AMT=DOSE RATE EVID MDV CMT CLX",
  "       V1X QX V2X SDIX SDSX",
  "$DATA example1.csv IGNORE=C",
  "$SUBROUTINES ADVAN3 TRANS4",
  "",
  "$PK",
  "MU_1=THETA(1)",
  "MU_2=THETA(2)",
  "MU_3=THETA(3)",
  "MU_4=THETA(4)",
  "CL=DEXP(MU_1+ETA(1))",
  "V1=DEXP(MU_2+ETA(2))",
  "Q=DEXP(MU_3+ETA(3))",
  "V2=DEXP(MU_4+ETA(4))",
  "S1=V1",
  "",
  "$ERROR",
  "Y = F + F*EPS(1)",
  "",
  "; Initial values of THETA",
  "$THETA",
  "(0.001, 2.0) ;[LN(CL)]",
  "(0.001, 2.0) ;[LN(V1)]",
  "(0.001, 2.0) ;[LN(Q)]",
  "(0.001, 2.0) ;[LN(V2)]",
  "",
  ";INITIAL values of OMEGA",
  "$OMEGA BLOCK(4)",
  "0.15   ;[P]",
  "0.01  ;[F]",
  "0.15   ;[P]",
  "0.01  ;[F]",
  "0.01  ;[F]",
  "0.15   ;[P]",
  "0.01  ;[F]",
  "0.01  ;[F]",
  "0.01  ;[F]",
  "0.15   ;[P]",
  "",
  ";Initial value of SIGMA",
  "$SIGMA",
  "(0.6 )   ;[P]",
  "",
  "$PRIOR NWPRI",
  "",
  "; Prior information of THETAS",
  "$THETAP (2.0 FIX)X4",
  "",
  "$THETAPV BLOCK(4) FIX VALUES(10000,0.0)",
  "",
  "; Prior information to the OMEGAS.",
  "$OMEGAP BLOCK(4) FIX VALUES(0.2,0.0)",
  "$OMEGAPD (4 FIX)",
  "",
  "; Prior information to the SIGMAS",
  "$SIGMAP 0.06 FIX",
  "$SIGMAPD (1 FIX)",
  "",
  "$EST METHOD=ITS MAPITER=0 INTERACTION FILE=example1.ext NITER=500",
  "     PRINT=5 NOABORT SIGL=4 CTYPE=3 CITER=10",
  "     CALPHA=0.05 NOPRIOR=1 NSIG=2",
  "",
  "$EST METHOD=SAEM INTERACTION NBURN=3000 NITER=500 PRINT=100",
  "     SEED=1556678 ISAMPLE=2",
  "",
  "$EST METHOD=IMP  INTERACTION EONLY=1 NITER=5 ISAMPLE=3000 PRINT=1",
  "     SIGL=8 NOPRIOR=1",
  "",
  "",
  "$EST METHOD=BAYES INTERACTION FILE=example1.txt NBURN=10000",
  "     NITER=10000 PRINT=100 NOPRIOR=0",
  "",
  "$EST METHOD=COND INTERACTION MAXEVAL=9999 NSIG=3 SIGL=10",
  "     PRINT=5 NOABORT NOPRIOR=1",
  "     FILE=example1.ext",
  "",
  "$COV MATRIX=R PRINT=E UNCONDITIONAL SIGL=12",
  "",
  "$TABLE ID TIME PRED RES WRES CPRED CWRES EPRED ERES EWRES NOAPPEND",
  "       ONEHEADER FILE=example1.TAB NOPRINT",
  "$TABLE ID CL V1 Q V2 FIRSTONLY NOAPPEND NOPRINT FILE=example1.PAR",
  "$TABLE ID ETA1 ETA2 ETA3 ETA4 FIRSTONLY NOAPPEND",
  "        NOPRINT FILE=example1.ETA"
)

nmex_a_uflg <- c(
  ";Model Desc: Receptor Mediated Clearance model with Dynamic Change in Receptors",
  "$PROB RUN# wexample6x (from r2compl), using FAST",
  "$ABBR DERIV2=NO DERIV2=NOCOMMON ; DERIV1=NO",
  "$INPUT C SET ID JID TIME DV AMT RATE EVID MDV CMT",
  "$DATA a_uflg.csv IGNORE=C IGNORE=(AMT.EQN.1.0) IGNORE=(RATE.EQN.1.0E+08)",
  "$SUBROUTINES ADVAN13 TRANS1 TOL=6 ATOL=6",
  "$MODEL NCOMPARTMENTS=3",
  "$OMEGA BLOCK(8) VALUES(0.5,0.01)",
  "$PK",
  "MU_1=THETA(1)",
  "MU_2=THETA(2)",
  "MU_3=THETA(3)",
  "MU_4=THETA(4)",
  "MU_5=THETA(5)",
  "MU_6=THETA(6)",
  "MU_7=THETA(7)",
  "MU_8=THETA(8)",
  "VC=EXP(MU_1+ETA(1))",
  "K10=EXP(MU_2+ETA(2))",
  "K12=EXP(MU_3+ETA(3))",
  "K21=EXP(MU_4+ETA(4))",
  "VM=EXP(MU_5+ETA(5))",
  "KMC=EXP(MU_6+ETA(6))",
  "K03=EXP(MU_7+ETA(7))",
  "K30=EXP(MU_8+ETA(8))",
  "S3=VC",
  "S1=VC",
  "KM=KMC*S1",
  "A_0(3)=K03/K30",
  "MTIME(1)=7.1",
  "MTDIFF=1",
  "AZTEST=A_0FLG",
  "IF(TSTATE==MTIME(1).AND.AZTEST==0) A_UFLG=1",
  "A_U(1)=A(1)+1000.0",
  "A_U(2)=A(2)",
  "A_U(3)=A(3)",
  "",
  "$DES",
  "DADT(1) = -(K10+K12)*A(1) + K21*A(2) - VM*A(1)*A(3)/(A(1)+KM)",
  "DADT(2) = K12*A(1) - K21*A(2)",
  "DADT(3) =  -(VM-K30)*A(1)*A(3)/(A(1)+KM) - K30*A(3) + K03",
  "",
  "$ERROR",
  "ETYPE=1",
  "IF(CMT.NE.1) ETYPE=0",
  "CP=A(1)/S1",
  "CR=A(3)/S3",
  "IPRE=CP",
  "IF(CMT.NE.1) IPRE=CR",
  "Y = IPRE + IPRE*ETYPE*EPS(1) + IPRE*(1.0-ETYPE)*EPS(2)",
  "",
  "$THETA",
  "( 4.0 )  ;[MU_1]",
  "( -3.1 ) ;[MU_2]",
  "( 0.5 )  ;[MU_3]",
  "( -0.2 );[MU_4]",
  "( 3.2 ) ;[MU_5]",
  "( 0.01 )  ;[MU_6]",
  "( 4.0 )  ;[MU_7]",
  "( -0.1) ;[MU_8]",
  "",
  "$SIGMA",
  "0.1 ;[p]",
  "0.1 ;[p]",
  "",
  "$EST METHOD=1 INTERACTION PRINT=1 NOABORT NOPRIOR=1 SIGL=6 MAXEVAL=0 NSIG=2 MCETA=10",
  "     NOTHETABOUNDTEST NOOMEGABOUNDTEST NOSIGMABOUNDTEST FAST"
)

#' @rdname nmrec_examples
#' @export
nmrec_examples <- list2env(
  list(
    "a_uflg" = nmex_a_uflg,
    "bayes1" = nmex_bayes1,
    "ccontrs" = nmex_ccontrs,
    "control3" = nmex_control3
  ),
  parent = emptyenv()
)
